In [34]:
# 데이터 프레임 행,열 선택 및 필터링 복습
import os
import pandas as pd

In [35]:
os.listdir('./drive/MyDrive/machine_learning/machine_learning_data')

['.ipynb_checkpoints', 'friend.csv', 'new_friend.csv', 'abalone.data']

In [36]:
base_src="./drive/MyDrive/machine_learning/machine_learning_data"
friend_src=base_src+"/friend.csv"
df=pd.read_csv(friend_src)
df.head()

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager

In [37]:
# index 2번에 해당하는 row 가져오기
df.iloc[2]

name       Nate
age          30
job     teacher
Name: 2, dtype: object

In [38]:
# column jobㅇ 해당되는 데이터 가져오기
df['job']

0      student
1    developer
2      teacher
3      dentist
4      manager
5       intern
Name: job, dtype: object

In [39]:
df.loc[:,'job']

0      student
1    developer
2      teacher
3      dentist
4      manager
5       intern
Name: job, dtype: object

In [40]:
# row 섞어서 불러올때는 loc나 iloc 활용하는거 추천

In [41]:
# 슬라이싱 기능 통해 여러 행 가져오기
df.iloc[[2,3]] #슬라이싱 사용 안함.

    name  age      job
2   Nate   30  teacher
3  Julia   40  dentist

In [42]:
df.iloc[2:4] #슬라이싱 써서 들고오기

    name  age      job
2   Nate   30  teacher
3  Julia   40  dentist

In [43]:
# 조건 필터링 가져오기
# 30대 이상만 가져오기
df['age']>=30

0    False
1     True
2     True
3     True
4     True
5    False
Name: age, dtype: bool

In [44]:
df[df['age']<30]

    name  age      job
0   John   20  student
5  Chris   25   intern

In [45]:
## job이 intern인 사람 가져오기
df[df['job']=='intern']

    name  age     job
5  Chris   25  intern

In [46]:
## 조건 여러개
# 30대 이상 40대 이하
df[(df['age']>=30) & (df['age']<=40)] # () & () 로 나타내주어야 여러개 조건 쓸 수 있다. 중요!

    name  age        job
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist

In [47]:
## 30대 미만 혹은 40대 초과(or function)
df[(df['age']<30) | (df['age']>40)]

    name  age      job
0   John   20  student
4  Brian   45  manager
5  Chris   25   intern

In [48]:
[1, 3, 5, 7, 11, 23]

[1, 3, 5, 7, 11, 23]

In [49]:
5 in [1, 3, 5, 7, 11, 23] # 데이터 하나. 단일값

True

In [50]:
# in을 통한 포함 조건 걸기 student와 manager인 친구만 고르고 싶을 때. == 사용 안하는 방법.
df[df['job'].apply(lambda x : x in ['student', 'manager'])] # series라서 위처럼 하면 안됨. .apply~ 이거 중요 꼭 기억하기

    name  age      job
0   John   20  student
4  Brian   45  manager

In [51]:
#데이터 전처리에서 가장 중요하고 많이 쓰이는 개념이다.

In [52]:
#  DataFrame 행, 열 삭제
import numpy as np
df = pd.DataFrame(np.arange(12).reshape(3,4), columns=['A', 'B', 'C', 'D'])
df

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [53]:
# B,C 컬럼 삭제
df.drop(['B', 'C'],axis=1, inplace=True)

In [54]:
# index 0, 1을 삭제하겠다.
df.drop([0,1])

   A   D
2  8  11

In [55]:
df= pd.read_csv(friend_src, encoding='utf-8')
df

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

In [56]:
# df를 하나 복사(원본 데이터 유지를 위해)
temp = df.copy()
temp

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

In [57]:
# age컬럼 모든 값을 변경
temp['age']=20
temp

    name  age        job
0   John   20    student
1  Jenny   20  developer
2   Nate   20    teacher
3  Julia   20    dentist
4  Brian   20    manager
5  Chris   20     intern

In [58]:
# 지정한 row의 column을 바꾸고 싶을 때
temp.loc[2,'age'] = 27
temp

    name  age        job
0   John   20    student
1  Jenny   20  developer
2   Nate   27    teacher
3  Julia   20    dentist
4  Brian   20    manager
5  Chris   20     intern

In [59]:
# groupby

In [60]:
os.listdir(base_src)

['.ipynb_checkpoints', 'friend.csv', 'new_friend.csv', 'abalone.data']

In [61]:
abalone_src = base_src + '/abalone.data'

In [62]:
abalone_df = pd.read_csv(abalone_src,header=None,sep=',',names=['sex', 'length', 'diameter', 'height', 'whole_weight',
                                                                 'shucked_weight', 'viscera_weight', 'shell_weight', 'rings'])
abalone_df

     sex  length  diameter  ...  viscera_weight  shell_weight  rings
0      M   0.455     0.365  ...          0.1010        0.1500     15
1      M   0.350     0.265  ...          0.0485        0.0700      7
2      F   0.530     0.420  ...          0.1415        0.2100      9
3      M   0.440     0.365  ...          0.1140        0.1550     10
4      I   0.330     0.255  ...          0.0395        0.0550      7
...   ..     ...       ...  ...             ...           ...    ...
4172   F   0.565     0.450  ...          0.2390        0.2490     11
4173   M   0.590     0.440  ...          0.2145        0.2605     10
4174   M   0.600     0.475  ...          0.2875        0.3080      9
4175   F   0.625     0.485  ...          0.2610        0.2960     10
4176   M   0.710     0.555  ...          0.3765        0.4950     12

[4177 rows x 9 columns]

In [63]:
# 1. 데이터 shape를 확인
# 딥러닝(CNN) => 이미지(데잍수, 가로, 세로, 채널) 4dimension
# 딥러닝(RNN) => 텍스트, 시계열 (데이터수, 가로, 세로) 3dimension
abalone_df.shape #찍어보고 dimesnion과 데이터 shape 확인

(4177, 9)

In [67]:
# 2. 데이터 결측값 확인(빈거 있는지)
abalone_df.isnull().sum().sum()  # True는 1, False는 0을 나타냄. sum 했을때 0이 아니면 결측값이 있다고 판단.

0

In [68]:
# 3. 기술통계 확인 # 연속형 변수만 확인 => numerical한 변수만 확인 가능.
abalone_df.describe() # 위 abalone_df와 비교할때 sex column이 없음. 문자형 카테고리컬 변수라서 mean, std, min등등이 없다.

            length     diameter  ...  shell_weight        rings
count  4177.000000  4177.000000  ...   4177.000000  4177.000000
mean      0.523992     0.407881  ...      0.238831     9.933684
std       0.120093     0.099240  ...      0.139203     3.224169
min       0.075000     0.055000  ...      0.001500     1.000000
25%       0.450000     0.350000  ...      0.130000     8.000000
50%       0.545000     0.425000  ...      0.234000     9.000000
75%       0.615000     0.480000  ...      0.329000    11.000000
max       0.815000     0.650000  ...      1.005000    29.000000

[8 rows x 8 columns]

In [70]:
# 전복(ablaone) 성별에 따라 groupby함수로 집계
#           DataFrame[집계변수].groupby(DataFrame[집계대상])
grouped=abalone_df['whole_weight'].groupby(abalone_df['sex'])

In [71]:
grouped.sum()

sex
F    1367.8175
I     578.8885
M    1514.9500
Name: whole_weight, dtype: float64

In [72]:
grouped.mean() # mean은 이상치에 대해서도 반응하므로, 이것만 보고서는 섣불리 판단하면 안된다.

sex
F    1.046532
I    0.431363
M    0.991459
Name: whole_weight, dtype: float64

In [73]:
grouped.size() # 개수

sex
F    1307
I    1342
M    1528
Name: whole_weight, dtype: int64

In [75]:
# 그룹변수가 하나가 아닌, 전체 연속형 변수에 대한 집계
abalone_df.groupby(abalone_df['sex']).mean()

       length  diameter    height  ...  viscera_weight  shell_weight      rings
sex                                ...
F    0.579093  0.454732  0.158011  ...        0.230689      0.302010  11.129304
I    0.427746  0.326494  0.107996  ...        0.092010      0.128182   7.890462
M    0.561391  0.439287  0.151381  ...        0.215545      0.281969  10.705497

[3 rows x 8 columns]

In [76]:
# 간단히 표현
abalone_df.groupby('sex').mean()

       length  diameter    height  ...  viscera_weight  shell_weight      rings
sex                                ...
F    0.579093  0.454732  0.158011  ...        0.230689      0.302010  11.129304
I    0.427746  0.326494  0.107996  ...        0.092010      0.128182   7.890462
M    0.561391  0.439287  0.151381  ...        0.215545      0.281969  10.705497

[3 rows x 8 columns]

In [80]:
# 새 조건에 맞는 변수 추가
abalone_df['length_bool'] = np.where(abalone_df['length']>abalone_df['length'].median(), 'length_long','length_short')

In [84]:
# 그룹변수를 2개 이상 선택해서 총계처리
abalone_df.groupby(['sex', 'length_bool']).mean() # EDA과정

                    length  diameter  ...  shell_weight      rings
sex length_bool                       ...
F   length_long   0.626895  0.493020  ...      0.360013  11.415073
    length_short  0.477428  0.373301  ...      0.178650  10.521531
I   length_long   0.584495  0.452952  ...      0.273247  10.585106
    length_short  0.402210  0.305893  ...      0.104549   7.451473
M   length_long   0.623359  0.489291  ...      0.351683  11.299172
    length_short  0.454875  0.353336  ...      0.162141   9.685053

[6 rows x 8 columns]

In [85]:
abalone_df.groupby(['sex','length_bool'])['whole_weight'].mean()

sex  length_bool
F    length_long     1.261330
     length_short    0.589702
I    length_long     0.923215
     length_short    0.351234
M    length_long     1.255182
     length_short    0.538157
Name: whole_weight, dtype: float64

In [88]:
# 중복 데이터 삭제(결측치 확인할때 같이 해주기)
# 중복된 row 확인
abalone_df.duplicated().sum()

0

In [98]:
# 중복 예제 생성을 위해 가상 중복데이터 생성
new_abalone = abalone_df.iloc[[0]]
new_abalone_df = pd.concat([abalone_df, new_ablaone],axis=0) # concat : 데이터 프레임 합칠때 사용
new_abalone_df

     sex  length  diameter  ...  shell_weight  rings   length_bool
0      M   0.455     0.365  ...        0.1500     15  length_short
1      M   0.350     0.265  ...        0.0700      7  length_short
2      F   0.530     0.420  ...        0.2100      9  length_short
3      M   0.440     0.365  ...        0.1550     10  length_short
4      I   0.330     0.255  ...        0.0550      7  length_short
...   ..     ...       ...  ...           ...    ...           ...
4173   M   0.590     0.440  ...        0.2605     10   length_long
4174   M   0.600     0.475  ...        0.3080      9   length_long
4175   F   0.625     0.485  ...        0.2960     10   length_long
4176   M   0.710     0.555  ...        0.4950     12   length_long
0      M   0.455     0.365  ...        0.1500     15  length_short

[4178 rows x 10 columns]

In [99]:
new_abalone_df.duplicated().sum()

1

In [100]:
# 뒤에꺼 살리고 첫번째거 없애고 싶을때
new_abalone_df.duplicated(keep='last')

0        True
1       False
2       False
3       False
4       False
        ...
4173    False
4174    False
4175    False
4176    False
0       False
Length: 4178, dtype: bool

In [101]:
# 중복 데이터 row 삭제
new_abalone_df.drop_duplicates()

     sex  length  diameter  ...  shell_weight  rings   length_bool
0      M   0.455     0.365  ...        0.1500     15  length_short
1      M   0.350     0.265  ...        0.0700      7  length_short
2      F   0.530     0.420  ...        0.2100      9  length_short
3      M   0.440     0.365  ...        0.1550     10  length_short
4      I   0.330     0.255  ...        0.0550      7  length_short
...   ..     ...       ...  ...           ...    ...           ...
4172   F   0.565     0.450  ...        0.2490     11   length_long
4173   M   0.590     0.440  ...        0.2605     10   length_long
4174   M   0.600     0.475  ...        0.3080      9   length_long
4175   F   0.625     0.485  ...        0.2960     10   length_long
4176   M   0.710     0.555  ...        0.4950     12   length_long

[4177 rows x 10 columns]

In [102]:
new_abalone_df

     sex  length  diameter  ...  shell_weight  rings   length_bool
0      M   0.455     0.365  ...        0.1500     15  length_short
1      M   0.350     0.265  ...        0.0700      7  length_short
2      F   0.530     0.420  ...        0.2100      9  length_short
3      M   0.440     0.365  ...        0.1550     10  length_short
4      I   0.330     0.255  ...        0.0550      7  length_short
...   ..     ...       ...  ...           ...    ...           ...
4173   M   0.590     0.440  ...        0.2605     10   length_long
4174   M   0.600     0.475  ...        0.3080      9   length_long
4175   F   0.625     0.485  ...        0.2960     10   length_long
4176   M   0.710     0.555  ...        0.4950     12   length_long
0      M   0.455     0.365  ...        0.1500     15  length_short

[4178 rows x 10 columns]

In [105]:
new_abalone_df.drop_duplicates(keep='last') # 중복값의 뒤에꺼 살릴때

     sex  length  diameter  ...  shell_weight  rings   length_bool
1      M   0.350     0.265  ...        0.0700      7  length_short
2      F   0.530     0.420  ...        0.2100      9  length_short
3      M   0.440     0.365  ...        0.1550     10  length_short
4      I   0.330     0.255  ...        0.0550      7  length_short
5      I   0.425     0.300  ...        0.1200      8  length_short
...   ..     ...       ...  ...           ...    ...           ...
4173   M   0.590     0.440  ...        0.2605     10   length_long
4174   M   0.600     0.475  ...        0.3080      9   length_long
4175   F   0.625     0.485  ...        0.2960     10   length_long
4176   M   0.710     0.555  ...        0.4950     12   length_long
0      M   0.455     0.365  ...        0.1500     15  length_short

[4177 rows x 10 columns]

In [106]:
new_abalone_df

     sex  length  diameter  ...  shell_weight  rings   length_bool
0      M   0.455     0.365  ...        0.1500     15  length_short
1      M   0.350     0.265  ...        0.0700      7  length_short
2      F   0.530     0.420  ...        0.2100      9  length_short
3      M   0.440     0.365  ...        0.1550     10  length_short
4      I   0.330     0.255  ...        0.0550      7  length_short
...   ..     ...       ...  ...           ...    ...           ...
4173   M   0.590     0.440  ...        0.2605     10   length_long
4174   M   0.600     0.475  ...        0.3080      9   length_long
4175   F   0.625     0.485  ...        0.2960     10   length_long
4176   M   0.710     0.555  ...        0.4950     12   length_long
0      M   0.455     0.365  ...        0.1500     15  length_short

[4178 rows x 10 columns]

In [108]:
# NaN(결측치) 찾아서 다른 값으로 변경
abalone_df.isnull().sum().sum() # 기존에는 결측치 없음

0

In [109]:
# 가상 결측치 생성
nan_abalone_df = abalone_df.copy()

In [110]:
nan_abalone_df.loc[2,'length'] = np.nan

In [113]:
nan_abalone_df.isnull().sum().sum()

1

In [115]:
# 결측치를 특정 값(0)으로 채우기
zero_abalone_df = nan_abalone_df.fillna(0)
zero_abalone_df

     sex  length  diameter  ...  shell_weight  rings   length_bool
0      M   0.455     0.365  ...        0.1500     15  length_short
1      M   0.350     0.265  ...        0.0700      7  length_short
2      F   0.000     0.420  ...        0.2100      9  length_short
3      M   0.440     0.365  ...        0.1550     10  length_short
4      I   0.330     0.255  ...        0.0550      7  length_short
...   ..     ...       ...  ...           ...    ...           ...
4172   F   0.565     0.450  ...        0.2490     11   length_long
4173   M   0.590     0.440  ...        0.2605     10   length_long
4174   M   0.600     0.475  ...        0.3080      9   length_long
4175   F   0.625     0.485  ...        0.2960     10   length_long
4176   M   0.710     0.555  ...        0.4950     12   length_long

[4177 rows x 10 columns]

In [116]:
# 결측치를 결측치가 속한 컬럼의 평균값으로 대체
nan_abalone_df.mean()

length            0.523991
diameter          0.407881
height            0.139516
whole_weight      0.828742
shucked_weight    0.359367
viscera_weight    0.180594
shell_weight      0.238831
rings             9.933684
dtype: float64

In [117]:
nan_abalone_df.fillna(nan_abalone_df.mean())

     sex    length  diameter  ...  shell_weight  rings   length_bool
0      M  0.455000     0.365  ...        0.1500     15  length_short
1      M  0.350000     0.265  ...        0.0700      7  length_short
2      F  0.523991     0.420  ...        0.2100      9  length_short
3      M  0.440000     0.365  ...        0.1550     10  length_short
4      I  0.330000     0.255  ...        0.0550      7  length_short
...   ..       ...       ...  ...           ...    ...           ...
4172   F  0.565000     0.450  ...        0.2490     11   length_long
4173   M  0.590000     0.440  ...        0.2605     10   length_long
4174   M  0.600000     0.475  ...        0.3080      9   length_long
4175   F  0.625000     0.485  ...        0.2960     10   length_long
4176   M  0.710000     0.555  ...        0.4950     12   length_long

[4177 rows x 10 columns]

In [121]:
# categorical 변수의 결측치인 경우
nan_abalone_df.loc[2,'sex'] = np.nan
sex_mode = nan_abalone_df['sex'].value_counts().sort_values(ascending=False).index[0]
sex_mode

'M'

In [122]:
nan_abalone_df['sex'].fillna(sex_mode)

0       M
1       M
2       M
3       M
4       I
       ..
4172    F
4173    M
4174    M
4175    F
4176    M
Name: sex, Length: 4177, dtype: object

In [123]:
# 데이터 프레임의 꽃
# apply 함수
# 활용
# 본인이 원하는 행과 열에 연산 혹은 function을 적용할 수 있다.
#열 기준 집계 : axis=0
#행 기준 집계 : axis=1

In [124]:
# 열 기준 집계_ axis=0은 row, axis=1은 column을 나타낸다고 생각하면, diameter의 전체 행들의 average를 집계한 것이다.
abalone_df[['diameter']].apply(np.average, axis=0)

diameter    0.407881
dtype: float64

In [126]:
# 행 기준 집계
abalone_df[['diameter']].apply(np.average,axis=1)

0       0.365
1       0.265
2       0.420
3       0.365
4       0.255
        ...
4172    0.450
4173    0.440
4174    0.475
4175    0.485
4176    0.555
Length: 4177, dtype: float64

In [133]:
# 사용자 함수를 통한 집계 ********** 중요
import math
def avg_ceil(x,y,z):
  return math.ceil((x+y+z)) # ceil은 올림.

abalone_df[['diameter','height','whole_weight']].apply(lambda x : avg_ceil(x[0],x[1],x[2]),axis=1)

0       1
1       1
2       2
3       2
4       1
       ..
4172    2
4173    2
4174    2
4175    2
4176    3
Length: 4177, dtype: int64

In [135]:
# 문제
# 사용자 정의 함수 사용
# ['diameter','height','whole_weight'] 변수 사용
# 세 변수의 합이 1이 넘으면 True, 아니면 False 출력 후 answer 변수에 저장
# abalone_df에 answer 열을  추가하고 입력.

In [153]:
# 내 답
def sum_data(x,y,z):
  return (x+y+z)>1
answer=abalone_df[['diameter','height','whole_weight']].apply(lambda x : sum_data(x[0],x[1],x[2]),axis=1)
abalone_df['answer']=answer
abalone_df

     sex  length  diameter  height  ...  shell_weight  rings   length_bool  answer
0      M   0.455     0.365   0.095  ...        0.1500     15  length_short   False
1      M   0.350     0.265   0.090  ...        0.0700      7  length_short   False
2      F   0.530     0.420   0.135  ...        0.2100      9  length_short    True
3      M   0.440     0.365   0.125  ...        0.1550     10  length_short    True
4      I   0.330     0.255   0.080  ...        0.0550      7  length_short   False
...   ..     ...       ...     ...  ...           ...    ...           ...     ...
4172   F   0.565     0.450   0.165  ...        0.2490     11   length_long    True
4173   M   0.590     0.440   0.135  ...        0.2605     10   length_long    True
4174   M   0.600     0.475   0.205  ...        0.3080      9   length_long    True
4175   F   0.625     0.485   0.150  ...        0.2960     10   length_long    True
4176   M   0.710     0.555   0.195  ...        0.4950     12   length_long    True

[4177 rows x 11 columns]

In [140]:
# 풀이
def f(x):
  sum_=x[0]+x[1]+x[2]
  if sum_>1:
    return True
  else:
    return False

answer=abalone_df[['diameter','height','whole_weight']].apply(lambda x : f(x),axis=1)

abalone_df['answer']=answer
abalone_df

     sex  length  diameter  height  ...  shell_weight  rings   length_bool  answer
0      M   0.455     0.365   0.095  ...        0.1500     15  length_short   False
1      M   0.350     0.265   0.090  ...        0.0700      7  length_short   False
2      F   0.530     0.420   0.135  ...        0.2100      9  length_short    True
3      M   0.440     0.365   0.125  ...        0.1550     10  length_short    True
4      I   0.330     0.255   0.080  ...        0.0550      7  length_short   False
...   ..     ...       ...     ...  ...           ...    ...           ...     ...
4172   F   0.565     0.450   0.165  ...        0.2490     11   length_long    True
4173   M   0.590     0.440   0.135  ...        0.2605     10   length_long    True
4174   M   0.600     0.475   0.205  ...        0.3080      9   length_long    True
4175   F   0.625     0.485   0.150  ...        0.2960     10   length_long    True
4176   M   0.710     0.555   0.195  ...        0.4950     12   length_long    True

[4177 rows x 11 columns]

In [143]:
# 컬럼 내 유니크한 값 뽑아서 갯수 확인( 카테고리변수)
abalone_df['sex'].value_counts(ascending=False) # ascending=False 까지하면 정렬. # (dropna=True)면 결측치 제외하고

M    1528
I    1342
F    1307
Name: sex, dtype: int64

In [147]:
# 두 개의 DataFrame 합치기 (계속)
# 가상 abalone ㅂ개 row 데이터 생성 및 결합
one_abalone_df=abalone_df.iloc[[0]]
pd.concat([abalone_df, one_abalone_df], axis=0)

     sex  length  diameter  height  ...  shell_weight  rings   length_bool  answer
0      M   0.455     0.365   0.095  ...        0.1500     15  length_short   False
1      M   0.350     0.265   0.090  ...        0.0700      7  length_short   False
2      F   0.530     0.420   0.135  ...        0.2100      9  length_short    True
3      M   0.440     0.365   0.125  ...        0.1550     10  length_short    True
4      I   0.330     0.255   0.080  ...        0.0550      7  length_short   False
...   ..     ...       ...     ...  ...           ...    ...           ...     ...
4173   M   0.590     0.440   0.135  ...        0.2605     10   length_long    True
4174   M   0.600     0.475   0.205  ...        0.3080      9   length_long    True
4175   F   0.625     0.485   0.150  ...        0.2960     10   length_long    True
4176   M   0.710     0.555   0.195  ...        0.4950     12   length_long    True
0      M   0.455     0.365   0.095  ...        0.1500     15  length_short   False

[4178 rows x 11 columns]

In [150]:
# 컬럼방향으로 붙이기.
one_abalone_df = abalone_df.iloc[:,[0]]
pd.concat([abalone_df, one_abalone_df], axis=1)

      sex  length  diameter  height  ...  rings   length_bool  answer  sex
0       M   0.455     0.365   0.095  ...     15  length_short   False    M
1       M   0.350     0.265   0.090  ...      7  length_short   False    M
2       F   0.530     0.420   0.135  ...      9  length_short    True    F
3       M   0.440     0.365   0.125  ...     10  length_short    True    M
4       I   0.330     0.255   0.080  ...      7  length_short   False    I
...   ...     ...       ...     ...  ...    ...           ...     ...  ...
4172    F   0.565     0.450   0.165  ...     11   length_long    True    F
4173    M   0.590     0.440   0.135  ...     10   length_long    True    M
4174    M   0.600     0.475   0.205  ...      9   length_long    True    M
4175    F   0.625     0.485   0.150  ...     10   length_long    True    F
4176    M   0.710     0.555   0.195  ...     12   length_long    True    M

[4177 rows x 12 columns]